In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])


In [4]:
arr*5

array([ 5, 10, 15, 20, 25, 30])

In [5]:
arr+1

array([2, 3, 4, 5, 6, 7])

In [6]:
arr.max()

6

In [7]:
arr.min()

1

In [9]:
np.flipud(arr)

array([6, 5, 4, 3, 2, 1])

In [10]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]

In [11]:
print(array_1[2:-3])

[3, 5, 4, 6, 7, 8]


In [12]:
import numpy as np

array_1 = np.array([1, 2, 3, 4])

array_2 = np.array([5, 6, 7, 8])

array_new = np.stack((array_1, array_2), axis=1)

print(array_new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [13]:
 a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [14]:
 import numpy

array1 = numpy.array([[1, 2, 3, 4, 5],[20,30,40,50,60]])

array2 = numpy.array([[6, 7, 8, 9, 10],[9,8,7,6,5]])

array1 = numpy.column_stack([array1, array2])

print(array1)



[[ 1  2  3  4  5  6  7  8  9 10]
 [20 30 40 50 60  9  8  7  6  5]]


AttributeError: 'list' object has no attribute 'elements'

: 