In [3]:
import numpy as np


In [5]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])

In [6]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [7]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
#Vertivally
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
np.vstack((arr2,arr1))

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0]])

In [10]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9,  0, 16, 17, 18, 19, 20]])

In [17]:
#Axix=0 vertically
arr=np.concatenate((arr1,arr2),axis=0)

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
arr3=np.concatenate((arr1,arr2),axis=1)

In [23]:
np.hsplit(arr3, 2)

[array([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]