In [3]:
import numpy as np


In [4]:
arr=np.array([[7,3,8,6,9],[7,8,9,10,8],[5,4,2,3,1]])

In [5]:
arr

array([[ 7,  3,  8,  6,  9],
       [ 7,  8,  9, 10,  8],
       [ 5,  4,  2,  3,  1]])

In [6]:
#Sort a array
np.sort(arr)

array([[ 3,  6,  7,  8,  9],
       [ 7,  8,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [8]:
#row wise sorting
np.sort(arr,axis=1,kind='mergesort')

array([[ 3,  6,  7,  8,  9],
       [ 7,  8,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [9]:
#col wise sort
np.sort(arr,axis=0,kind='mergesort')

array([[ 5,  3,  2,  3,  1],
       [ 7,  4,  8,  6,  8],
       [ 7,  8,  9, 10,  9]])