In [1]:
import numpy as np


In [18]:
array=np.random.random((3,3))
array

array([[0.99690431, 0.79967289, 0.20376851],
       [0.48563078, 0.00201385, 0.16973246],
       [0.42311559, 0.63380217, 0.62001762]])

In [12]:
if np.random.random()>0.5:
    print("Run the functions")
else:
    print("None")

Run the functions


In [13]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [16]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])